# Generated by Django 6.0.2 on 2026-02-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder_lat', models.FloatField()),
                ('responder_lon', models.FloatField()),
                ('victim_lat', models.FloatField()),
                ('victim_lon', models.FloatField()),
                ('severity', models.IntegerField()),
                ('route_type', models.CharField(max_length=20)),
                ('eta_minutes', models.FloatField(blank=True, null=True)),
                ('safety_score', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('helicopter_recommended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
